### ISSUE TITLE
Unexpected token '?'.

### ISSUE THREAD

**Issue by reach2jeyan** [JSanchezIO/junit-testrail-reporter#1]
This is the command i m trying to

npx junit-testrail-reporter -p=test-results-o.xml -h=TESTRAIL_HOST -TESTRAIL_PASSWORD=TESTRAIL_PASSWORD -projectId=1 -u=username

the Documentation does not have an argument for the TESTRAIL_PASSWORD

So I ended up using `env variable`

**Comment by JSanchezIO** [comment]
If you're using an environment variable you may need to alter you command a bit. Assuming, you're using bash:

```bash
npx junit-testrail-reporter -p=test-results-o.xml -h="$TESTRAIL_HOST" -projectId=1 -u=username
```

You won't have to specify `TESTRAIL_PASSWORD` because the CLI will automatically check for `process.env.TESTRAIL_PASSWORD`. So as long as the environment variable is set before you run your command it should work fine. You can run `export TESTRAIL_PASSWORD='SOME_PASSWORD'` to set the environment variable in the current shell.

**Comment by reach2jeyan** [comment]
So I switched to `bash` with `exec bash` and  confirmed my environment variable here
```
bash-3.2$ echo $TESTRAIL_PASSWORD
somepassword
bash-3.2$ echo $TESTRAIL_HOST
https://xyz.testrail.io
```
I have got the `TESTRAIL_PASSWORD` stored in the bash_profile as well and have `sourced it` too


and then I ran the command you had posted in the earlier reply, but I would still get `unexpected token '?'

**Comment by JSanchezIO** [comment]
Interesting. What version of node and npm are you running?

**Comment by reach2jeyan** [comment]
```
abc@xyz-MacBook-Pro % npm -v
6.14.8
abc@xyz-MacBook-Pro  % node -v
v12.19.1
```

**Comment by JSanchezIO** [comment]
If possible, can you try running it with Node 14 and 16?

**Comment by JSanchezIO** [comment]
Understood. Is it possible to run it outside of the desired project with Node 14 or 16? I'm trying to determine if it's the Node version or something other configuration. If it's a lower version of Node, I can update the TypeScript to output JS supported by Node 12.

**Comment by JSanchezIO** [comment]
Currently, yes. I can see about pushing out a fix version to make it compatible with Node 12.

**Comment by JSanchezIO** [comment]
Feel free to try out v1.1.1 and see if it resolves your issue.

**Comment by reach2jeyan** [comment]
@JSanchezIO thanks for reverting so fast. this works right now with node 12. thanks a lot :)
