### ISSUE TITLE
Not able to see New Run getting created in testrail 

### ISSUE THREAD

**Issue by mnataraj17** [JSanchezIO/junit-testrail-reporter#2]
junit report thats been generated looks like below
<img width="1404" alt="Screen Shot 2022-04-28 at 11 35 03 AM" src="https://user-images.githubusercontent.com/92099129/165790192-22b7f5c8-ad93-420a-84d9-32fb2eab0a0f.png">

Try 1: 
Command I am using is 
`npx junit-testrail-reporter -p='results.xml' -h='https://companyname.testrail.io' -projectId=1 -r='playwright-tests' -u='test@abc.com'`

and I have exported password using `export TESTRAIL_PASSWORD=password`

Error message: `[junit-testrail-reporter]  TypeError: glob pattern string required`

Try 2:
Exported all variables except p value and executing with
`npx junit-testrail-reporter -p='results.xml'   `

Response: `[junit-testrail-reporter]  Finished!`
But I don't see new run getting created on Testrail

Node version used: 17

Not sure what I am missing. Your help will be highly appreciated. thanks!

**Comment by JSanchezIO** [comment]
Are you still experiencing this issue?

**Comment by mnataraj17** [comment]
Yes. It would be great if you could help me with resolving the issue. Thanks!

**Comment by JSanchezIO** [comment]
Are you seeing any logs similar to `Successfully created and closed TestRail run...`?

**Comment by mnataraj17** [comment]
Nothing else, just the messages I mentioned above

**Comment by mnataraj17** [comment]
Is there anything I am missing from my side which can be found in above message?

**Comment by JSanchezIO** [comment]
I don't believe so, I'm going to add some more logging statements to see where it's stopping execution. I believe it's stopping here: https://github.com/JSanchezIO/junit-testrail-reporter/blob/main/src/reporter.ts#L206

I will push a new patch version with the logging, which you can then install so we can learn more.

**Comment by JSanchezIO** [comment]
v1.2.0 has been published, please install that and see if you get the new warning

**Comment by mnataraj17** [comment]
Thank you so much for pushing updated code. 
I Installed v1.2.0, tried both methods mentioned above in the issue description : Can see same response, no new logs are visible. Not sure if I am missing something here. 
It would be great if you could help resolve. Thanks!

**Comment by JSanchezIO** [comment]
Can you attach the XML so I can mess with it locally?

**Comment by mnataraj17** [comment]
Looks like I can't attach .xml filetype. let me paste the xml content here.


`<testsuites id="" name="" tests="1" failures="1" skipped="0" errors="0" time="31.244">
<testsuite name="accountTests.spec.ts" timestamp="1653655418148" hostname="" tests="1" failures="1" skipped="0" time="30.22" errors="0">
<testcase name="S1 C828 Verify account update @account" classname="[chromium] › accountTests.spec.ts:5:1 › S1 C828 Verify account update @account" time="30.22">
<failure message="accountTests.spec.ts:5:1 S1 C828 Verify account update @account" type="FAILURE">
  [chromium] › accountTests.spec.ts:5:1 › S1 C828 Verify account update @account ===================

    Timeout of 30000ms exceeded.

    locator.hover: Target closed
    =========================== logs ===========================
    waiting for selector "[alt=logo]"
    ============================================================

      14 |   await tenantPage.selectTenant(process.env.TENANT_DOMAIN);
      15 |   await expect(page.url()).toContain(process.env.TENANT_DOMAIN);
    > 16 |   await navPage.hoverTenantLogo();
         |   ^
      17 |   await navPage.clickSettings();
      18 |   await accountPage.verifyAccountPageLoaded();
      19 |   await accountPage.enterFirstName(firstName);

        at NavigationPage.hoverTenantLogo (/Users/megha_nataraj/Documents/Repos/cm-client-ui-test-automation/pages/navigation.page.ts:24:23)
        at /Users/username/Documents/Repos/cm-client-ui-test-automation/tests/accountTests.spec.ts:16:3

    Pending operations:
      - locator.hover at pages/navigation.page.ts:24:23


    attachment #1: video (video/webm) --------------------------------------------------------------
    test-results/accountTests-S1-C828-Verify-account-update-account-chromium/video.webm
    ------------------------------------------------------------------------------------------------

    attachment #2: screenshot (image/png) ----------------------------------------------------------
    test-results/accountTests-S1-C828-Verify-account-update-account-chromium/test-failed-1.png
    ------------------------------------------------------------------------------------------------

</failure>
<system-out>

[[ATTACHMENT|../test-results/accountTests-S1-C828-Verify-account-update-account-chromium/video.webm]]

[[ATTACHMENT|../test-results/accountTests-S1-C828-Verify-account-update-account-chromium/test-failed-1.png]]

</system-out>
</testcase>
</testsuite>
</testsuites>`

**Comment by mnataraj17** [comment]
[results.txt](https://github.com/JSanchezIO/junit-testrail-reporter/files/8786753/results.txt)

**Comment by JSanchezIO** [comment]
Try using v1.3.0 and see if you get any additional logs

**Comment by mnataraj17** [comment]
Thanks for pushing the updated version.
Able to see new logs now!
`[junit-testrail-reporter]  TypeError: Only absolute URLs are supported

[junit-testrail-reporter]  Finished!`

Not sure what does this mean though.

**Comment by JSanchezIO** [comment]
What are you setting the host to?

**Comment by mnataraj17** [comment]
I was just sending **companyname.testrail.io** previously. But it is working totally fine now after sending full URL **https://companyname.testrail.io**

**Comment by mnataraj17** [comment]
Thanks for all the help. @JSanchezIO

**Comment by mnataraj17** [comment]
I have a question. Right now, it is creating new run and adding testcases, test results and then closing the run. what do I have to do if I don't want test run to be closed?
