### ISSUE TITLE
Question: Can we skip closing the test run?

### ISSUE THREAD

**Issue by mnataraj17** [JSanchezIO/junit-testrail-reporter#4]
Is there any way I can skip closing the test run once the test results are uploaded in a new run?
Currently not all of the testcases are automated so we would like to add remaining testcases to same test run and then continue executing. For this I would need to skip closing the test run when it uploads results. It would be great if you could help me with this. Thanks!

**Comment by JSanchezIO** [comment]
This has been addressed in v1.4.0
