### ISSUE TITLE
Skipped tests leads to empty test run creation

### ISSUE THREAD

**Issue by mnataraj17** [JSanchezIO/junit-testrail-reporter#5]
If there are tests skipped (with status : Untested) in the execution, this will result in a test run with all tests "untested" status on Testrail with error message as : TestRailException: Field :results.status_id uses an invalid status (Untested).

It would be great if this skipped test are handled and added to testrail run with "Untested" status and passed tests and failed tests are not ignored while creating test run.
Thanks!

**Comment by JSanchezIO** [comment]
This repository has been moved to https://github.com/JSanchezIO/JSanchezIO/blob/main/packages/junit-testrail-reporter. Please re-open your issue over there if this behavior is still occurring.
